Repository SolSolHigh/SolSolHigh-FE, pull requests merged in 2024-08, with the labels that each got.

#2 [Chore/#1] README 초안 작성
  .github/pull_request_template.md
  README.md
  docs/docker.svg
  docs/ec2.svg
  docs/githubactions.svg
  docs/mswjs.svg
  docs/nginx.svg
  docs/react.svg
  docs/recoil.svg
  docs/storybook.svg
  docs/tailwindcss.svg
  docs/tanstackquery.png
  docs/typescript.svg
Labels: 📐 Chore

#4 [Chore/#3] 개발환경 초기 세팅
  ssh-web/.gitignore
  ssh-web/.storybook/main.ts
  ssh-web/.storybook/preview.ts
  ssh-web/README.md
  ssh-web/package-lock.json
  ssh-web/package.json
  ssh-web/public/favicon.ico
  ssh-web/public/index.html
  ssh-web/public/logo192.png
  ssh-web/public/logo512.png
  ssh-web/public/manifest.json
  ssh-web/public/robots.txt
  ssh-web/src/App.css
  ssh-web/src/App.test.tsx
  ssh-web/src/App.tsx
  ssh-web/src/index.css
  ssh-web/src/index.tsx
  ssh-web/src/logo.svg
  ssh-web/src/react-app-env.d.ts
  ssh-web/src/reportWebVitals.ts
  ssh-web/src/setupTests.ts
  ssh-web/src/stories/Button.stories.ts
  ssh-web/src/stories/Button.tsx
  ssh-web/src/stories/Configure.mdx
  ssh-web/src/stories/Header.stories.ts
  ssh-web/src/stories/Header.tsx
  ssh-web/src/stories/Page.stories.ts
  ssh-web/src/stories/Page.tsx
  ssh-web/src/stories/assets/accessibility.png
  ssh-web/src/stories/assets/accessibility.svg
  ssh-web/src/stories/assets/addon-library.png
  ssh-web/src/stories/assets/assets.png
  ssh-web/src/stories/assets/avif-test-image.avif
  ssh-web/src/stories/assets/context.png
  ssh-web/src/stories/assets/discord.svg
  ssh-web/src/stories/assets/docs.png
  ssh-web/src/stories/assets/figma-plugin.png
  ssh-web/src/stories/assets/github.svg
  ssh-web/src/stories/assets/share.png
  ssh-web/src/stories/assets/styling.png
  ssh-web/src/stories/assets/testing.png
  ssh-web/src/stories/assets/theming.png
  ssh-web/src/stories/assets/tutorials.svg
  ssh-web/src/stories/assets/youtube.svg
  ssh-web/src/stories/button.css
  ssh-web/src/stories/header.css
  ssh-web/src/stories/page.css
  ssh-web/tailwind.config.js
  ssh-web/tsconfig.json
Labels: 📐 Chore

#7 [Chore/#5] axios, msw, recoil 기본 설정
  ssh-web/package.json
  ssh-web/public/mockServiceWorker.js
  ssh-web/src/App.tsx
  ssh-web/src/apis/interceptors.ts
  ssh-web/src/atoms/example.ts
  ssh-web/src/index.tsx
  ssh-web/src/mocks/browser.ts
  ssh-web/src/mocks/handlers.ts
Labels: 📐 Chore, 📣 Merge

#10 [Chore/#9] axios url 도메인 타이핑
  ssh-web/src/App.tsx
  ssh-web/src/apis/axiosConfig.ts
Labels: 📐 Chore, 📣 Merge

#14 [Chore/#11] tv 사용한 아토믹 버튼 설계 초안
  ssh-web/package-lock.json
  ssh-web/package.json
  ssh-web/src/App.tsx
  ssh-web/src/components/atoms/Button/Button.styles.ts
  ssh-web/src/components/atoms/Button/Button.types.ts
  ssh-web/src/components/atoms/Button/index.tsx
Labels: 📐 Chore, 📣 Merge

#13 [Chore/#6] setting storybook
  ssh-web/.storybook/preview.ts
  ssh-web/package-lock.json
  ssh-web/src/stories/Button.stories.ts
  ssh-web/src/stories/Button.stories.tsx
  ssh-web/src/stories/Button.tsx
  ssh-web/src/stories/Header.stories.ts
  ssh-web/src/stories/Header.tsx
  ssh-web/src/stories/Page.stories.ts
  ssh-web/src/stories/Page.tsx
  ssh-web/src/stories/header.css
  ssh-web/src/stories/page.css
  ssh-web/src/stories/tailwind.css
  ssh-web/tailwind.config.js
Labels: 📐 Chore, 📣 Merge

#16 [Chore/#15] 프론트엔드 CI/CD 구축
  .github/workflows/deploy.yml
  ssh-web/Dockerfile
  ssh-web/nginx.conf
  ssh-web/package-lock.json
Labels: 📐 Chore, 📣 Merge

#18 [Chore/#17] Toast, Tanstack Query, Skeleton Atom 도입
  ssh-web/package-lock.json
  ssh-web/package.json
  ssh-web/src/App.tsx
  ssh-web/src/apis/Example/index.ts
  ssh-web/src/apis/interceptors.ts
  ssh-web/src/components/atoms/Skeleton/Skeleton.styles.ts
  ssh-web/src/components/atoms/Skeleton/Skeleton.types.ts
  ssh-web/src/components/atoms/Skeleton/index.tsx
  ssh-web/src/index.tsx
  ssh-web/src/interfaces/Example.ts
  ssh-web/src/interfaces/User.ts
  ssh-web/src/mocks/exampleHandler.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/mocks/userHandler.ts
  ssh-web/src/utils/toastUtil.tsx
  ssh-web/tailwind.config.js
Labels: 📐 Chore, 📣 Merge

#22 [Feat/#21] Icon, Typography atoms component 구현
  ssh-web/.storybook/custom.css
  ssh-web/.storybook/main.ts
  ssh-web/.storybook/preview.ts
  ssh-web/.storybook/tailwind.css
  ssh-web/src/components/atoms/Icon/Icon.styles.ts
  ssh-web/src/components/atoms/Icon/Icon.types.ts
  ssh-web/src/components/atoms/Icon/Index.stories.tsx
  ssh-web/src/components/atoms/Icon/index.tsx
  ssh-web/src/components/atoms/Typography/Typography.styles.ts
  ssh-web/src/components/atoms/Typography/Typography.types.ts
  ssh-web/src/components/atoms/Typography/index.stories.tsx
  ssh-web/src/components/atoms/Typography/index.tsx
  ssh-web/src/components/molecules/.gitkeep
  ssh-web/src/components/organisms/.gitkeep
  ssh-web/src/themes/themeBase.ts
  ssh-web/tailwind.config.js
Labels: ✨ Feat, 📣 Merge

#25 [Feat/#24] 로그인 페이지 UI 구현
  ssh-web/public/assets/kakao_login.png
  ssh-web/public/assets/mascot_top.png
  ssh-web/public/assets/naver_login.png
  ssh-web/src/App.tsx
  ssh-web/src/components/atoms/Typography/Typography.styles.ts
  ssh-web/src/components/atoms/Typography/Typography.types.ts
  ssh-web/src/components/molecules/.gitkeep
  ssh-web/src/components/molecules/LoginNav/LoginNav.styles.ts
  ssh-web/src/components/molecules/LoginNav/LoginNav.types.ts
  ssh-web/src/components/molecules/LoginNav/index.stories.tsx
  ssh-web/src/components/molecules/LoginNav/index.tsx
  ssh-web/src/index.css
  ssh-web/src/index.tsx
  ssh-web/src/pages/Home/index.tsx
  ssh-web/src/pages/Login/index.tsx
  ssh-web/src/themes/themeBase.ts
  ssh-web/tailwind.config.js
Labels: ✨ Feat, 📣 Merge

#29 [Feat/#23] 라우터 세팅 + 반응형 Navigation(+Notification), Modal 개발
  ssh-web/src/App.tsx
  ssh-web/src/atoms/modal.ts
  ssh-web/src/atoms/resize.ts
  ssh-web/src/components/atoms/BackdropFilter/index.tsx
  ssh-web/src/components/atoms/Icon/Icon.styles.ts
  ssh-web/src/components/atoms/Icon/Icon.types.ts
  ssh-web/src/components/molecules/IconNavButtonWithLabel/index.tsx
  ssh-web/src/components/molecules/Modal/ModalCloseButton.tsx
  ssh-web/src/components/molecules/Modal/ModalContent.tsx
  ssh-web/src/components/molecules/Modal/index.tsx
  ssh-web/src/components/molecules/TextNavButton/index.tsx
  ssh-web/src/components/organisms/NavigationBar/index.tsx
  ssh-web/src/hook/index.ts
  ssh-web/src/hook/useCloseModalOnRouteChange.ts
  ssh-web/src/hook/useLockBodyScroll.ts
  ssh-web/src/hook/useResizeDetection.ts
  ssh-web/src/index.tsx
  ssh-web/src/interfaces/routerInterface.ts
  ssh-web/src/pages/Home.tsx
  ssh-web/src/themes/themeBase.ts
  ssh-web/src/utils/router.tsx
  ssh-web/tailwind.config.js
Labels: ✨ Feat, 📣 Merge

#31 [Feat/#30] Button Atom 컴포넌트 확장 개발, 스토리북 추가
  ssh-web/src/components/atoms/Button/Button.styles.ts
  ssh-web/src/components/atoms/Button/Button.types.ts
  ssh-web/src/components/atoms/Button/index.stories.tsx
  ssh-web/src/components/atoms/Button/index.tsx
  ssh-web/src/components/molecules/IconNavButtonWithLabel/index.tsx
  ssh-web/src/pages/Home.tsx
Labels: ✨ Feat, 📣 Merge

#37 [Feat/#36] CircularImage Atom + AvatarWithLabel Molecules구현
  ssh-web/public/assets/images/samples/children/boy1.png
  ssh-web/public/assets/images/samples/children/boy2.png
  ssh-web/public/assets/images/samples/children/boy3.png
  ssh-web/public/assets/images/samples/children/girl1.png
  ssh-web/public/assets/images/samples/children/girl2.png
  ssh-web/public/assets/images/samples/children/girl3.png
  ssh-web/src/components/atoms/CircularImage/CircularImage.stories.tsx
  ssh-web/src/components/atoms/CircularImage/CircularImage.styles.ts
  ssh-web/src/components/atoms/CircularImage/CircularImage.types.ts
  ssh-web/src/components/atoms/CircularImage/index.tsx
  ssh-web/src/components/molecules/AvatarWithLabel/AvatarWihLabel.types.ts
  ssh-web/src/components/molecules/AvatarWithLabel/AvatarWithLabel.stories.tsx
  ssh-web/src/components/molecules/AvatarWithLabel/AvatarWithLabel.styles.ts
  ssh-web/src/components/molecules/AvatarWithLabel/index.tsx
Labels: ✨ Feat, 📣 Merge

#35 [Feat/#34] Badge Atom 컴포넌트 구현
  ssh-web/src/components/atoms/Badge/Badge.stories.tsx
  ssh-web/src/components/atoms/Badge/Badge.styles.ts
  ssh-web/src/components/atoms/Badge/Badge.types.ts
  ssh-web/src/components/atoms/Badge/index.tsx
Labels: ✨ Feat, 📣 Merge

#39 [Feat/#32] 퀴즈 풀이 페이지
  ssh-web/src/components/molecules/QuizDetail/QuizDetail.styles.tsx
  ssh-web/src/components/molecules/QuizDetail/QuizDetail.types.tsx
  ssh-web/src/components/molecules/QuizDetail/index.stories.tsx
  ssh-web/src/components/molecules/QuizDetail/index.tsx
  ssh-web/src/interfaces/quizInterface.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/pages/QuizSolving/styles.ts
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#42 [Feat/#33] ToggleTab Atom 구현
  ssh-web/src/components/atoms/ToggleTab/ToggleTab.stories.tsx
  ssh-web/src/components/atoms/ToggleTab/ToggleTab.styles.ts
  ssh-web/src/components/atoms/ToggleTab/ToggleTab.types.ts
  ssh-web/src/components/atoms/ToggleTab/index.tsx
Labels: ✨ Feat, 📣 Merge

#44 [Feat/#41] 생일 선택 페이지 포함 회원가입 최종 완성
  ssh-web/src/atoms/signup.ts
  ssh-web/src/components/atoms/TextField/TextField.types.ts
  ssh-web/src/components/atoms/TextField/index.tsx
  ssh-web/src/components/molecules/NumberDial/index.tsx
  ssh-web/src/components/organisms/BirthdayForm/BirthdayForm.styles.ts
  ssh-web/src/components/organisms/BirthdayForm/BirthdayForm.types.ts
  ssh-web/src/components/organisms/BirthdayForm/index.stories.tsx
  ssh-web/src/components/organisms/BirthdayForm/index.tsx
  ssh-web/src/components/organisms/UserInfoForm/index.tsx
  ssh-web/src/interfaces/userInterface.ts
  ssh-web/src/pages/Signup/index.tsx
Labels: ✨ Feat, 📣 Merge

#45 [Feat/#33] 미션 페이지 ( 아이 ) 구현 & Divider Atom 구현을 비롯한 기타 부수작업
  ssh-web/src/App.tsx
  ssh-web/src/atoms/modal.ts
  ssh-web/src/components/atoms/BackdropFilter/index.tsx
  ssh-web/src/components/atoms/Badge/Badge.styles.ts
  ssh-web/src/components/atoms/Divider/Divider.stories.tsx
  ssh-web/src/components/atoms/Divider/Divider.styles.ts
  ssh-web/src/components/atoms/Divider/Divider.types.ts
  ssh-web/src/components/atoms/Divider/index.tsx
  ssh-web/src/components/molecules/MissionCard/MissionCard.stories.tsx
  ssh-web/src/components/molecules/MissionCard/MissionCard.styles.ts
  ssh-web/src/components/molecules/MissionCard/index.tsx
  ssh-web/src/components/molecules/MissionDetail/MissionDetail.stories.tsx
  ssh-web/src/components/molecules/MissionDetail/MissionDetail.styles.ts
  ssh-web/src/components/molecules/MissionDetail/MissionDetail.types.ts
  ssh-web/src/components/molecules/MissionDetail/index.tsx
  ssh-web/src/components/molecules/MissionList/MissionList.stories.tsx
  ssh-web/src/components/molecules/MissionList/MissionList.styles.ts
  ssh-web/src/components/molecules/MissionList/MissionList.types.ts
  ssh-web/src/components/molecules/MissionList/index.tsx
  ssh-web/src/components/molecules/Modal/ModalContent.tsx
  ssh-web/src/components/molecules/Modal/index.tsx
  ssh-web/src/components/organisms/NavigationBar/index.tsx
  ssh-web/src/hook/useCloseModalOnRouteChange.ts
  ssh-web/src/interfaces/missionInterfaces.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Home.tsx
  ssh-web/src/pages/Mission/children/LoadingSkeleton.tsx
  ssh-web/src/pages/Mission/children/index.tsx
  ssh-web/src/pages/Mission/children/styles.ts
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/pages/Signup/index.tsx
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#49 [Feat/#48] 사용자 정보 조회 페이지 구현
  ssh-web/public/assets/images/samples/parent/man1.png
  ssh-web/public/assets/images/samples/parent/man2.png
  ssh-web/public/assets/images/samples/parent/woman1.png
  ssh-web/public/assets/images/samples/parent/woman2.png
  ssh-web/src/App.tsx
  ssh-web/src/components/molecules/InfoList/InfoList.stories.tsx
  ssh-web/src/components/molecules/InfoList/InfoList.styles.ts
  ssh-web/src/components/molecules/InfoList/InfoList.types.ts
  ssh-web/src/components/molecules/InfoList/index.tsx
  ssh-web/src/components/molecules/MascotCard/MascotCard.types.ts
  ssh-web/src/components/molecules/MascotCard/index.tsx
  ssh-web/src/interfaces/userInterface.ts
  ssh-web/src/pages/Information/Manage/index.tsx
  ssh-web/src/pages/Information/Manage/styles.ts
  ssh-web/src/pages/Information/index.tsx
  ssh-web/src/pages/Information/styles.ts
  ssh-web/src/utils/router.tsx
  ssh-web/tailwind.config.js
Labels: ✨ Feat, 📣 Merge

#51 [Chore/#50] 배포 방식의 변경으로 일부 우선 머지
  .github/workflows/deploy.yml
  ssh-web/nginx.conf
  ssh-web/src/components/molecules/LoginNav/index.tsx
Labels: 📐 Chore, 📣 Merge

#52 [Feat/#46] 미션 (부모 확장) 페이지 구현 등
  ssh-web/src/apis/missionApi.ts
  ssh-web/src/components/molecules/IconNavButtonWithLabel/index.tsx
  ssh-web/src/components/molecules/MissionDetail/MissionDetail.stories.tsx
  ssh-web/src/components/molecules/MissionDetail/MissionDetail.types.ts
  ssh-web/src/components/molecules/MissionDetail/index.tsx
  ssh-web/src/components/molecules/MissionList/MissionList.types.ts
  ssh-web/src/components/molecules/MissionList/index.tsx
  ssh-web/src/components/molecules/Modal/ModalContent.tsx
  ssh-web/src/components/molecules/NumberDial/NumberDial.stories.tsx
  ssh-web/src/components/molecules/NumberDial/NumberDial.types.ts
  ssh-web/src/components/molecules/NumberDial/index.tsx
  ssh-web/src/components/molecules/TextNavButton/index.tsx
  ssh-web/src/interfaces/missionInterfaces.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Mission/child/LoadingSkeleton.tsx
  ssh-web/src/pages/Mission/child/MissionCreate/MissionCreate.styles.ts
  ssh-web/src/pages/Mission/child/MissionCreate/index.tsx
  ssh-web/src/pages/Mission/child/index.tsx
  ssh-web/src/pages/Mission/child/styles.ts
  ssh-web/src/pages/Mission/index.tsx
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#53 [Feat/#40] 퀴즈 메인페이지 구현
  ssh-web/src/App.tsx
  ssh-web/src/components/atoms/ProfileIcon.zip
  ssh-web/src/components/atoms/ProfileIcon/ProfileIcon.styles.ts
  ssh-web/src/components/atoms/ProfileIcon/ProfileIcon.types.ts
  ssh-web/src/components/atoms/ProfileIcon/abc.png
  ssh-web/src/components/atoms/ProfileIcon/index.stories.tsx
  ssh-web/src/components/atoms/ProfileIcon/index.tsx
  ssh-web/src/components/molecules/ChangeChild/ChangeChild.styles.tsx
  ssh-web/src/components/molecules/ChangeChild/index.tsx
  ssh-web/src/components/molecules/QuizDetail/QuizDetail.types.tsx
  ssh-web/src/components/molecules/QuizModal/ModalCloseButton.tsx
  ssh-web/src/components/molecules/QuizModal/ModalContent.tsx
  ssh-web/src/components/molecules/QuizModal/index.tsx
  ssh-web/src/components/organisms/QuizKeywordTab/QuizKeywordTab.types.tsx
  ssh-web/src/components/organisms/QuizKeywordTab/index.tsx
  ssh-web/src/components/organisms/QuizLogsDetailModal/index.tsx
  ssh-web/src/components/organisms/QuizTab/QuizTabProps.types.tsx
  ssh-web/src/components/organisms/QuizTab/index.tsx
  ssh-web/src/interfaces/quizInterface.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/QuizMain/index.tsx
  ssh-web/src/pages/QuizMain/styles.ts
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/pages/QuizSolving/styles.ts
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#55 [Feat/#50] 로그인 api 를 위한 머지
  ssh-web/src/apis/interceptors.ts
  ssh-web/src/apis/userApi.ts
  ssh-web/src/components/molecules/LoginNav/index.tsx
Labels: ✨ Feat, 📣 Merge

#58 [Feat/#54] 약속권 페이지 구현
  ssh-web/public/assets/images/common/addphoto.png
  ssh-web/public/assets/images/common/defaultImg.webp
  ssh-web/public/assets/images/common/promiseImg.png
  ssh-web/src/components/atoms/ProfileIcon.zip
  ssh-web/src/components/atoms/ProfileIcon/ProfileIcon.styles.ts
  ssh-web/src/components/atoms/ProfileIcon/ProfileIcon.types.ts
  ssh-web/src/components/atoms/ProfileIcon/abc.png
  ssh-web/src/components/atoms/ProfileIcon/index.stories.tsx
  ssh-web/src/components/atoms/ProfileIcon/index.tsx
  ssh-web/src/components/molecules/AddPromiseCard/AddPromiseCard.types.tsx
  ssh-web/src/components/molecules/AddPromiseCard/index.tsx
  ssh-web/src/components/molecules/PromiseItem/PromiseItem.styles.tsx
  ssh-web/src/components/molecules/PromiseItem/PromiseItem.types.tsx
  ssh-web/src/components/molecules/PromiseItem/index.tsx
  ssh-web/src/components/molecules/PromiseItem/stemp.png
  ssh-web/src/components/molecules/QuizModal/ModalContent.tsx
  ssh-web/src/components/organisms/AddPromiseModal/AddPromiseModal.types.tsx
  ssh-web/src/components/organisms/AddPromiseModal/index.tsx
  ssh-web/src/components/organisms/ConfirmPromiseModal/ConfirmPromiseModal.types.tsx
  ssh-web/src/components/organisms/ConfirmPromiseModal/index.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/PromiseDetailModal.styles.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/PromiseDetailModal.types.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/index.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/promiseImg.png
  ssh-web/src/components/organisms/QuizLogsDetailModal/QuizLogsDetailModal.types.tsx
  ssh-web/src/components/organisms/QuizLogsDetailModal/index.tsx
  ssh-web/src/components/organisms/QuizTab/index.tsx
  ssh-web/src/components/organisms/QuizTab/styles.tsx
  ssh-web/src/interfaces/promiseTicketInterface.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Promise/index.tsx
  ssh-web/src/pages/Promise/styles.ts
  ssh-web/src/pages/QuizMain/index.tsx
  ssh-web/src/pages/QuizMain/styles.ts
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#66 [Feat/#64] FCM 알림 수신 기능 구현
  ssh-web/.gitignore
  ssh-web/env
  ssh-web/package-lock.json
  ssh-web/package.json
  ssh-web/public/firebase-messaging-sw.js
  ssh-web/src/App.tsx
  ssh-web/src/apis/fcmApi.ts
  ssh-web/src/atoms/signin.ts
  ssh-web/src/firebase/Message.tsx
  ssh-web/src/firebase/firebaseConfig.js
  ssh-web/src/pages/Login/styles.ts
  ssh-web/tsconfig.json
Labels: ✨ Feat, 📣 Merge

#67 [Feat/#59] 계좌 UI 구현
  ssh-web/public/assets/images/common/family.png
  ssh-web/src/components/atoms/ProgressBar/ProgressBar.styles.tsx
  ssh-web/src/components/atoms/ProgressBar/ProgressBar.types.tsx
  ssh-web/src/components/atoms/ProgressBar/index.stories.tsx
  ssh-web/src/components/atoms/ProgressBar/index.tsx
  ssh-web/src/components/molecules/ChangeChild/index.tsx
  ssh-web/src/components/molecules/QuizModal/ModalContent.tsx
  ssh-web/src/components/organisms/AddPromiseModal/AddPromiseModal.types.tsx
  ssh-web/src/components/organisms/AddPromiseModal/index.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/index.tsx
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Account/Child/index.tsx
  ssh-web/src/pages/Account/Parent/index.tsx
  ssh-web/src/pages/Account/index.tsx
  ssh-web/src/pages/AccountItem/index.tsx
  ssh-web/src/pages/IntroductionAccount/family.png
  ssh-web/src/pages/IntroductionAccount/index.tsx
  ssh-web/src/pages/Promise/index.tsx
  ssh-web/src/pages/QuizMain/index.tsx
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#72 [Feat/#71] UI 개선 - 1
  .github/workflows/deploy.yml
  ssh-web/public/assets/mascot_study.png
  ssh-web/src/App.tsx
  ssh-web/src/components/molecules/ChangeChild/index.tsx
  ssh-web/src/components/organisms/QuizTab/index.tsx
  ssh-web/src/pages/Main.tsx
  ssh-web/src/pages/Mission/index.tsx
Labels: ✨ Feat, 📣 Merge

#73 [Fix/#61] 사용자 도메인 리팩토링, 라우터 수정
  .github/workflows/deploy.yml
  .vscode/settings.json
  ssh-web/public/assets/images/experience/task-done.png
  ssh-web/src/App.tsx
  ssh-web/src/apis/interceptors.ts
  ssh-web/src/apis/promiseApi.ts
  ssh-web/src/apis/userApi.ts
  ssh-web/src/components/molecules/LevelCard/index.tsx
  ssh-web/src/components/molecules/MascotCard/MascotCard.types.ts
  ssh-web/src/components/molecules/MascotCard/index.tsx
  ssh-web/src/components/organisms/NavigationBar/index.tsx
  ssh-web/src/hook/useSessionCheck.ts
  ssh-web/src/interfaces/userInterface.ts
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Home/HomeChild.tsx
  ssh-web/src/pages/Home/HomeParent.tsx
  ssh-web/src/pages/Information/InformationFetch.tsx
  ssh-web/src/pages/Information/Manage/ManageChildFetch.tsx
  ssh-web/src/pages/Information/Manage/ManageParentFetch.tsx
  ssh-web/src/pages/Menu/MenuChild.tsx
  ssh-web/src/pages/Menu/MenuParent.tsx
  ssh-web/src/pages/Promise/index.tsx
  ssh-web/src/pages/Signup/index.tsx
  ssh-web/src/utils/appUtil.ts
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 🔧 Fix, 📣 Merge

#74 [Feat/#68] 약속권, 퀴즈 api 연결
  .github/workflows/deploy.yml
  ssh-web/src/components/molecules/ChangeChild/ChangeChild,types.tsx
  ssh-web/src/components/molecules/ChangeChild/index.tsx
  ssh-web/src/components/organisms/ConfirmPromiseModal/ConfirmPromiseModal.types.tsx
  ssh-web/src/components/organisms/ConfirmPromiseModal/index.tsx
  ssh-web/src/components/organisms/PromiseDetailModal/PromiseDetailModal.types.tsx
  ssh-web/src/components/organisms/QuizKeywordTab/index.tsx
  ssh-web/src/components/organisms/QuizTab/index.tsx
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Account/Child/index.tsx
  ssh-web/src/pages/Account/Parent/index.tsx
  ssh-web/src/pages/Account/index.tsx
  ssh-web/src/pages/Promise/index.tsx
  ssh-web/src/pages/QuizMain/index.tsx
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/utils/router.tsx
Labels: ✨ Feat, 📣 Merge

#76 [Feat/#71] 계란/마켓 관련 UI 개선
  .github/workflows/deploy.yml
  ssh-web/src/components/molecules/EggCard/EggCard.styles.ts
  ssh-web/src/pages/Egg/components/Lottie/ConfettiLottie.tsx
  ssh-web/src/pages/Egg/components/Lottie/LoadingLottie.tsx
  ssh-web/src/pages/Egg/components/PriceChart.tsx
  ssh-web/src/pages/Egg/components/TodayEgg.tsx
Labels: ✨ Feat

#77 [Fix/#61] 기능 수정
  ssh-web/src/components/molecules/MascotCard/index.tsx
  ssh-web/src/components/organisms/NavigationBar/index.tsx
  ssh-web/src/pages/Egg/EggFetch.styles.ts
  ssh-web/src/pages/Egg/EggFetch.tsx
  ssh-web/src/pages/Egg/components/TodayEgg.tsx
  ssh-web/src/pages/Information/InformationFetch.tsx
  ssh-web/src/pages/Information/Manage/ManageParentFetch.tsx
  ssh-web/src/pages/Information/Request/RequestFetch.tsx
  ssh-web/src/pages/Mission/MissionCreate/MissionCreate.styles.ts
  ssh-web/src/pages/Mission/MissionCreate/index.tsx
  ssh-web/src/pages/Mission/index.tsx
  ssh-web/src/pages/Promise/styles.ts
  ssh-web/src/utils/appUtil.ts
Labels: 🔧 Fix, 📣 Merge

#78 [Feat/#75] 송금기능, 계좌 해지 시도시 AI 이미지 생성
  .github/workflows/deploy.yml
  ssh-web/src/mocks/index.ts
  ssh-web/src/pages/Account/Child/index.tsx
  ssh-web/src/pages/AccountItem/index.tsx
  ssh-web/src/pages/QuizSolving/Crying.png
  ssh-web/src/pages/QuizSolving/index.tsx
  ssh-web/src/pages/QuizSolving/yay.png
Labels: ✨ Feat, 📣 Merge
